# Generated by Django 3.1.5 on 2021-01-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='respondent_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('respondent_id', 'question', 'answer'), name='unique_answers'),
        ),
    ]
